// config.js - Centralized configuration 
require('dotenv').config();

const config = {
    MONGODB_URL: process.env.MONGODB_URL || '',
    DB_NAME: process.env.DB_NAME || 'baga',
    COLLECTIONS: { SESSIONS: 'whatsapp_sessions', NUMBERS: 'active_numbers', CONFIGS: 'bot_configs' },
    AUTO_VIEW_STATUS: 'true',
    AUTO_STATUS_REACT: 'false',
    AUTO_STATUS_REPLY: 'false',
    STATUS_REPLY_MSG: '*_Your status viewed successfully by Syed zada X niazi 𝐌𝐃 🤖_*',
    AUTO_RECORDING: 'false',
    AUTO_REACT: 'false',
    AUTO_TYPING: 'false',
    ALWAYS_ONLINE: 'false',
    VERSION: '4.0.0 Bᴇᴛᴀ',
    DESCRIPTION: '*© POWERED BY Syed zada X niazi 𝐌𝐃*',
    ANTI_DELETE_PATH: 'inbox',
    ANTI_DELETE: 'false',
    ANTI_EDIT_PATH: 'inbox',
    ANTI_EDIT: 'false',
    STICKER_NAME: 'Syed zada X niazi 𝐌𝐃',
    STICKER_AUTHOR: 'Niazi 𝐌𝐃',
    ANTI_LINK: 'true',
    ANTI_LINK_ACTION: 'warn',
    WELCOME: 'false',
    GOODBYE: 'false',
    WELCOME_MESSAGE: '*_@user joined the group, welcome! 🎉_*',
    GOODBYE_MESSAGE: '*_@user has left the group, we will miss them! 👋_*',
    ADMIN_ACTION: 'false',
    MODE: 'public',
    PREFIX: '.',
    ANTI_CALL: 'false',
    REJECT_MSG: '*Call Rejected Automatically 📵*',
    READ_MESSAGE: 'false',
    AUTO_STATUS_SEEN: 'true',
    OWNER_REACT: 'false',
    CUSTOM_REACT: 'false',
    HEART_REACT: 'false',
    CUSTOM_EMOJIS: ['😊', '👍', '🚀', '💻', '🎉', '🔥'],
    HEART_EMOJIS: ['❤️', '💖', '💝', '💗', '💓', '💞', '💕', '💟', '♥️', '❤️‍🔥', '❤️‍🩹'],
    OWNER_EMOJIS: ['❤️', '🧡', '💛', '💚', '🩵', '💙', '💜', '🩷', '🤎', '🖤', '🩶', '🤍', '❤️‍🔥', '❤️‍🩹', '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '♥️'],
    REACT_EMOJIS: ['❤️','🔥','👏','😮','😢','👍','🎉','🙏','😍','😊','🥰','💕','🤩','✨','😎','🥳','🙌','💖','💗','💓','💞','💘','💝','💟','❣️','♥️','❤️‍🔥','❤️‍🩹','🧡','💛','💚','🩵','💙','💜','🩷','🤍','🤎','🖤','🩶','🌹','🌺','🌸','💐','🌷','🪷','🌻','🌼','⭐','🌟','💫','✨','⚡','☀️','🌈','☄️','👑','💎','🏆','🥇','🎖️','🏅','🎁','🎀','🧸','🍫','🍭','🍬','🦋','🕊️','🦢','🦚','🦜','🐬','🐳','🐠','🍓','🍒','🍑','🍍','🥭','🍉','🍇','🎵','🎶','🎤','🎧','🎸','🎹','🚀','🛸','🌍','🌎','🌏','🌙','⭐','💯','✔️','✅','☑️','💥','💫','🫶','🤝','💪','🏖️','🌊','⛱️','🏝️','🌅','🌄','🎇','🎆','🎊','🎈','🎂','🍰','🧁','💌','📩','📨','💍','💐','🪄','🔮','🪙','💠','🔷','🔹','🔸','🔶','🕯️','🪔','🏵️','🎗️','🌠','🌌','🫰','🤲','🙌','🙏','💐','💝','♾️','☘️','🍀','🌿','🌱','🌴','🎋','🧿','🪬','💎','👑','🏰','🗝️'],
    BOT_NAME: 'Syed zada X niazi',
    OWNER_NAME: 'Soni shah',
    OWNER_NUMBER: '923214384602',
    DEV: '923214384602',
    IK_IMAGE_PATH: './lib/love.jpg',
    BOT_IMAGE: './lib/love.jpg',
    CHANNEL_NAME: 'Syed zada X niazi 𝐌𝐃',
    MAX_RETRIES: Number(process.env.MAX_SESSIONS || 50),
    OTP_EXPIRY: 300000,
    BANNED: [],
    SUDO: ["923214384602@s.whatsapp.net"],
    MAIN_CHANNEL_URL: 'https://whatsapp.com/channel/0029Vb8txJmHFxOzJAlR1y2r',
    NEWSLETTER_JIDS: ['120363430848275148@newsletter','120363432170480200@newsletter','120363414261697647@newsletter','','','','',''],
    DEFAULT_SETTINGS: { 
        AUTO_VIEW_STATUS: 'true', AUTO_STATUS_SEEN: 'true', AUTO_STATUS_REACT: 'false', AUTO_STATUS_REPLY: 'false',
        STATUS_REPLY_MSG: '*_Your status viewed successfully by Syed zada X niazi 𝐌𝐃 🤖_*', READ_MESSAGE: 'false',
        AUTO_RECORDING: 'false', AUTO_REACT: 'false', AUTO_TYPING: 'false', ALWAYS_ONLINE: 'false',
        OWNER_REACT: 'false', CUSTOM_REACT: 'false', HEART_REACT: 'false',
        CUSTOM_EMOJIS: ['😊','👍','🚀','💻','🎉','🔥'],
        HEART_EMOJIS: ['❤️','💖','💝','💗','💓','💞','💕','💟','♥️','❤️‍🔥','❤️‍🩹'],
        ANTI_DELETE: 'false', ANTI_DELETE_PATH: 'inbox', ANTI_EDIT: 'false', ANTI_EDIT_PATH: 'inbox',
        ANTI_CALL: 'false', ANTI_LINK: 'true', ANTI_LINK_ACTION: 'warn',
        WELCOME: 'false', GOODBYE: 'false', ADMIN_ACTION: 'false',
        WELCOME_MESSAGE: '*_@user joined the group, welcome! 🎉_*',
        GOODBYE_MESSAGE: '*_@user has left the group, we will miss them! 👋_*',
        REJECT_MSG: '*Call Rejected Automatically 📵*',
        VERSION: '4.0.0 Bᴇᴛᴀ', OWNER_NAME: 'Soni shah', OWNER_NUMBER: '923214384602', DEV: '923214384602',
        DESCRIPTION: '*© POWERED BY Syed zada X niazi 𝐌𝐃*', STICKER_NAME: 'Syed zada X niazi 𝐌𝐃',
        STICKER_AUTHOR: 'Niazi 𝐌𝐃', MODE: 'public', PREFIX: '.', BOT_NAME: 'Syed zada X niazi',
        CHANNEL_NAME: 'Syed zada X niazi 𝐌𝐃', MAIN_CHANNEL_URL: 'https://whatsapp.com/channel/0029Vb8txJmHFxOzJAlR1y2r',
        NEWSLETTER_JIDS: ['120363430848275148@newsletter','120363432170480200@newsletter','120363414261697647@newsletter','','','','','',''],
        BOT_IMAGE: './lib/love.jpg',
        REACT_EMOJIS: ['😂','❤️','🔥','👏','😮','😢','🤣','👍','🎉','🤔','🙏','😍','😊','🥰','💕','🤩','✨','😎','🥳','🙌'],
        OWNER_EMOJIS: ['❤️','🔥','👑','⭐','💎'], BANNED: [], SUDO: ["923214384602@s.whatsapp.net"]
    }
};

module.exports = config;
